### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by jackbibby1** [JarningGau/ProjectSVR#1]
Hi there,

I've just noticed that I'm recently getting Google Analytics data from your ProjectSVR package. It looks like your "_pkgdown.yml" has the same ganalytics id as my SCPA site (G-W1XR84YEPZ). I'm trying to figure out if this is an issue with your .yml file, or if it's coming from Google's side. Could you just check that you're entering the right measurement ID in your .yml file?

Thanks
Jack

**Comment by JarningGau** [comment]
Sorry for that. I copy the _pkgdown.yml file of the SCPA site as a template. Now I have removed the ganalytic id.

**Comment by jackbibby1** [comment]
No worries -- thanks
