### ISSUE TITLE
进行ProjectSVR::MapQuery时内存使用高

### ISSUE THREAD

**Issue by OrigamiSheep** [JarningGau/ProjectSVR#2]
Jarning老师，我的单细胞输入的样本是这个
> seu.q
An object of class Seurat 
22934 features across 136387 samples within 1 assay 
Active assay: RNA (22934 features, 0 variable features)

运行这一步的时候，内存使用超过370G仍然没有结束
seu.q <- ProjectSVR::MapQuery(seu.q, reference = reference, add.map.qual = T, ncores = 20)

#### Compute Gene Set Score Matrix ####
Using 'counts' slot for computing gene module score.
#### Map Query to Reference ####
L2 normalization ...
#### Map Quality ####
Building k-NN graph in feature space ...
Calculating euclidean metric on pred.emb ...

Calculating euclidean metric on pred.emb这一步需要的内存巨大超过370G，请问这样怎么办呢？

**Comment by JarningGau** [comment]
Check the new version of `MapQuery ` function
https://jarninggau.github.io/ProjectSVR/news/index.html#projectsvr-021

Now you can adopt the following code when map a large Seurat object.
```R
seu.q <- ProjectSVR::MapQuery(seu.q, reference, split.by = "orig.ident")
```
